### ISSUE TITLE
could not load module libvl

### ISSUE THREAD

**Issue by jrabary** [IHPSystems/VLFeat.jl#1]
Hi
I'm trying to use this package but got the following error (for example with vl_hog) 

`ERROR: error compiling vl_hog: could not load module libvl: libvl`

Any ideas ?

**Comment by kmsquire** [comment]
Hi, @jrabary, sorry, I haven't set this package up yet to install the library, so you'll have to do it yourself for now. 

What platform are you on?

I also haven't worked much on the package beyond the HOG descriptor (and I wasn't really happy with the implementation here of that). I'll try to add some basic info, at least. 

Cheers!

**Comment by jrabary** [comment]
Hi @kmsquire. I'm using julia on a debian box with and version of vlfeat that I compiled myself. I'm relatively new to julia, I descover it this week :) so there's lot of thing that I don't undersand yet.

**Comment by stemann** [comment]
This should be fixed by #4.
