### ISSUE TITLE
Can you upgrade to compatible julia v1.0 ??

### ISSUE THREAD

**Issue by zsz02** [IHPSystems/VLFeat.jl#10]
The repository  is very useful !!!
Can you upgrade to compatible julia v1.0 ??

**Comment by stemann** [comment]
It’s on the to-do list, but currently we do not have the time.

A PR is welcome.

**Comment by stemann** [comment]
WIP:
1. JLL: https://github.com/JuliaPackaging/Yggdrasil/pull/5342
2. Update C wrapper using JLL and [Clang.jl binding generator](https://github.com/JuliaInterop/Clang.jl#binding-generator)

**Comment by stemann** [comment]
Done: https://github.com/IHPSystems/VLFeat.jl/commit/ca02c3aab2a0511ea6070efe50001fe6ffb50823
