### ISSUE TITLE
LoadError: ccall: could not find function for inline functions

### ISSUE THREAD

**Issue by nstiurca** [IHPSystems/VLFeat.jl#7]
It seems that the function bindings fail in the case of inlined C functions. Ie,

```
using Images
using TestImages
using VLFeat
I = convert(Image{ColorTypes.Gray{Float32}}, testimage("lena_gray_256"))
noctaves = -1
nlevels = 3
o_min = 0
sift_obj = vl_sift_new(width(I), height(I), noctaves, nlevels, o_min)
err = vl_sift_process_first_octave(sift_obj, pointer(I.data))
vl_sift_detect(sift_obj)
keypoints = vl_sift_get_keypoints(sift_obj)
```

results in

```
ERROR: ccall: could not find function vl_sift_get_keypoints in library /home/<user>/.julia/v0.4/VLFeat/deps/usr/lib/libvl.so
 in vl_sift_get_keypoints at /home/<user>/.julia/v0.4/VLFeat/src/libvl/sift.jl:200
```

Poking around in `/home/<user>/.julia/v0.4/VLFeat/deps/src/vlfeat-0.9.20/vl/sift.h`, I found 

```
nl /home/<user>/.julia/v0.4/VLFeat/deps/src/vlfeat-0.9.20/vl/sift.h | grep get_keypo -B 1 -A 4
   130  VL_INLINE vl_sift_pix *vl_sift_get_octave  (VlSiftFilt const *f, int s) ;
   131  VL_INLINE VlSiftKeypoint const *vl_sift_get_keypoints (VlSiftFilt const *f) ;
   132  /** @} */

   133  /** @name Set parameters
   134   ** @{
--
   238  VL_INLINE VlSiftKeypoint const *
   239  vl_sift_get_keypoints (VlSiftFilt const *f)
   240  {
   241    return f-> keys ;
   242  }
```

which explains why the function isn't found in the library.

Do you know of any fix/workaround for this? I'm not terribly well versed in `ccall` stuff.

**Comment by stemann** [comment]
You can only call exported funktions via ccall. I were able to work around the issue of in-lined functions for the SIFT implementation - see the Julia implementation of vl_sift.

**Comment by nstiurca** [comment]
Thanks. I hadn't realized it's relatively easy to cast the pointers to Julia types which mirror the C structs like that, so I'll be able to work around the issue.

Still, the Julia functions are currently broken, so I will leave this bug open. :)

**Comment by stemann** [comment]
Should be working now.
